-- fwd.forecast_identity rows: structural dedup/leakage keys (leaf_index + book_id bound at seal)
-- F01: (FINAL_RULE_PUBLICATIONS_REGARDING_GPU_SH, TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY, >=, enactment of matching investment mandate for 200,000+ GB300 shipments, 2027-12-31)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F01, 'F01', 'FINAL_RULE_PUBLICATIONS_REGARDING_GPU_SH', 'TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY', '>=', 'enactment of matching investment mandate for 200,000+ GB300 shipments', '2027-12-31', 0.22, fwd_private.forecast_identity_v1('FINAL_RULE_PUBLICATIONS_REGARDING_GPU_SH','TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY','>=','enactment of matching investment mandate for 200,000+ GB300 shipments','2027-12-31'));
-- F02: (ANNUAL_EUROPEAN_TECHNOLOGY_SPENDING, TOPIC:EUROSTAT, >=, greater than 1.5 trillion euros, 2027-12-31)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F02, 'F02', 'ANNUAL_EUROPEAN_TECHNOLOGY_SPENDING', 'TOPIC:EUROSTAT', '>=', 'greater than 1.5 trillion euros', '2027-12-31', 0.78, fwd_private.forecast_identity_v1('ANNUAL_EUROPEAN_TECHNOLOGY_SPENDING','TOPIC:EUROSTAT','>=','greater than 1.5 trillion euros','2027-12-31'));
-- F03: (EUROPEAN_AVAILABILITY_STATUS_OF_ADVANCED, TOPIC:META-PLATFORMS-NEWSROOM, bool, commercial availability restored, 2028-02-01)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F03, 'F03', 'EUROPEAN_AVAILABILITY_STATUS_OF_ADVANCED', 'TOPIC:META-PLATFORMS-NEWSROOM', 'bool', 'commercial availability restored', '2028-02-01', 0.25, fwd_private.forecast_identity_v1('EUROPEAN_AVAILABILITY_STATUS_OF_ADVANCED','TOPIC:META-PLATFORMS-NEWSROOM','bool','commercial availability restored','2028-02-01'));
-- F04: (ACTIVE_IS-INFORMED_LETTER_RESTRICTIONS_O, TOPIC:U.S.-FEDERAL-REGISTER, bool, license requirement active, 2028-06-12)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F04, 'F04', 'ACTIVE_IS-INFORMED_LETTER_RESTRICTIONS_O', 'TOPIC:U.S.-FEDERAL-REGISTER', 'bool', 'license requirement active', '2028-06-12', 0.8, fwd_private.forecast_identity_v1('ACTIVE_IS-INFORMED_LETTER_RESTRICTIONS_O','TOPIC:U.S.-FEDERAL-REGISTER','bool','license requirement active','2028-06-12'));
-- F05: (ACTIVE_SECTION_232_IMPORT_ADJUSTMENT_ORD, TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE, bool, proclamation remains in effect, 2028-08-06)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F05, 'F05', 'ACTIVE_SECTION_232_IMPORT_ADJUSTMENT_ORD', 'TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE', 'bool', 'proclamation remains in effect', '2028-08-06', 0.7, fwd_private.forecast_identity_v1('ACTIVE_SECTION_232_IMPORT_ADJUSTMENT_ORD','TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE','bool','proclamation remains in effect','2028-08-06'));
-- F06: (OPERATIONAL_EUROHPC_AI_FACTORIES_COUNT, TOPIC:EUROHPC-JOINT-UNDERTAKING, >=, greater than 19, 2028-12-31)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F06, 'F06', 'OPERATIONAL_EUROHPC_AI_FACTORIES_COUNT', 'TOPIC:EUROHPC-JOINT-UNDERTAKING', '>=', 'greater than 19', '2028-12-31', 0.65, fwd_private.forecast_identity_v1('OPERATIONAL_EUROHPC_AI_FACTORIES_COUNT','TOPIC:EUROHPC-JOINT-UNDERTAKING','>=','greater than 19','2028-12-31'));
-- F07: (EUROPEAN_AI_INFRASTRUCTURE_INVESTMENT_VO, TOPIC:NVIDIA-FINANCIAL-REPORTS, <=, reduction below tripled investment level, 2029-12-31)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F07, 'F07', 'EUROPEAN_AI_INFRASTRUCTURE_INVESTMENT_VO', 'TOPIC:NVIDIA-FINANCIAL-REPORTS', '<=', 'reduction below tripled investment level', '2029-12-31', 0.38, fwd_private.forecast_identity_v1('EUROPEAN_AI_INFRASTRUCTURE_INVESTMENT_VO','TOPIC:NVIDIA-FINANCIAL-REPORTS','<=','reduction below tripled investment level','2029-12-31'));
-- F08: (EXPORT_LICENSING_POLICY_STATUS_FOR_H200_, TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY, bool, case-by-case review policy active, 2030-01-15)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F08, 'F08', 'EXPORT_LICENSING_POLICY_STATUS_FOR_H200_', 'TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY', 'bool', 'case-by-case review policy active', '2030-01-15', 0.75, fwd_private.forecast_identity_v1('EXPORT_LICENSING_POLICY_STATUS_FOR_H200_','TOPIC:U.S.-BUREAU-OF-INDUSTRY-AND-SECURITY','bool','case-by-case review policy active','2030-01-15'));
-- F09: (ACTIVE_STATUS_OF_JANUARY_2026_SEMICONDUC, TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE, bool, formal repeal enacted, 2031-01-14)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F09, 'F09', 'ACTIVE_STATUS_OF_JANUARY_2026_SEMICONDUC', 'TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE', 'bool', 'formal repeal enacted', '2031-01-14', 0.32, fwd_private.forecast_identity_v1('ACTIVE_STATUS_OF_JANUARY_2026_SEMICONDUC','TOPIC:THE-WHITE-HOUSE-PRESS-OFFICE','bool','formal repeal enacted','2031-01-14'));
-- F10: (ANNUAL_EUROPEAN_PRIVATE_AI_INVESTMENT_VO, TOPIC:CES-INTELLIGENCE-MARKET-ANALYSIS, bool, greater than 20 billion dollars, 2031-08-09)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F10, 'F10', 'ANNUAL_EUROPEAN_PRIVATE_AI_INVESTMENT_VO', 'TOPIC:CES-INTELLIGENCE-MARKET-ANALYSIS', 'bool', 'greater than 20 billion dollars', '2031-08-09', 0.28, fwd_private.forecast_identity_v1('ANNUAL_EUROPEAN_PRIVATE_AI_INVESTMENT_VO','TOPIC:CES-INTELLIGENCE-MARKET-ANALYSIS','bool','greater than 20 billion dollars','2031-08-09'));
