-- fwd.forecast_identity rows: structural dedup/leakage keys (leaf_index + book_id bound at seal)
-- F01: (PERCENTAGE_OF_NEW_AI_VENTURE_CAPITAL_FUN, TOPIC:FINANCIAL-TIMES, bool, exceeding 70%, 2028-08-09)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F01, 'F01', 'PERCENTAGE_OF_NEW_AI_VENTURE_CAPITAL_FUN', 'TOPIC:FINANCIAL-TIMES', 'bool', 'exceeding 70%', '2028-08-09', 0.75, fwd_private.forecast_identity_v1('PERCENTAGE_OF_NEW_AI_VENTURE_CAPITAL_FUN','TOPIC:FINANCIAL-TIMES','bool','exceeding 70%','2028-08-09'));
-- F02: (NUMBER_OF_NEW_FEDERAL_AI_REGULATIONS_AND, TOPIC:THE-WALL-STREET-JOURNAL, bool, at least 3 significant pieces of legislation, 2027-12-09)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F02, 'F02', 'NUMBER_OF_NEW_FEDERAL_AI_REGULATIONS_AND', 'TOPIC:THE-WALL-STREET-JOURNAL', 'bool', 'at least 3 significant pieces of legislation', '2027-12-09', 0.75, fwd_private.forecast_identity_v1('NUMBER_OF_NEW_FEDERAL_AI_REGULATIONS_AND','TOPIC:THE-WALL-STREET-JOURNAL','bool','at least 3 significant pieces of legislation','2027-12-09'));
-- F03: (NUMBER_OF_NEW_MULTILATERAL_AGREEMENTS_ON, TOPIC:REUTERS, bool, at least 4 significant new agreements, 2031-04-29)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F03, 'F03', 'NUMBER_OF_NEW_MULTILATERAL_AGREEMENTS_ON', 'TOPIC:REUTERS', 'bool', 'at least 4 significant new agreements', '2031-04-29', 0.85, fwd_private.forecast_identity_v1('NUMBER_OF_NEW_MULTILATERAL_AGREEMENTS_ON','TOPIC:REUTERS','bool','at least 4 significant new agreements','2031-04-29'));
-- F04: (AVERAGE_PRICE_VOLATILITY_INDEX_FOR_KEY_A, TOPIC:BLOOMBERG, bool, above 25%, 2029-04-27)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F04, 'F04', 'AVERAGE_PRICE_VOLATILITY_INDEX_FOR_KEY_A', 'TOPIC:BLOOMBERG', 'bool', 'above 25%', '2029-04-27', 0.7, fwd_private.forecast_identity_v1('AVERAGE_PRICE_VOLATILITY_INDEX_FOR_KEY_A','TOPIC:BLOOMBERG','bool','above 25%','2029-04-27'));
-- F05: (NUMBER_OF_COUNTRIES_IMPLEMENTING_MANDATO, TOPIC:FINANCIAL-TIMES, bool, at least 12 countries, 2030-03-13)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F05, 'F05', 'NUMBER_OF_COUNTRIES_IMPLEMENTING_MANDATO', 'TOPIC:FINANCIAL-TIMES', 'bool', 'at least 12 countries', '2030-03-13', 0.75, fwd_private.forecast_identity_v1('NUMBER_OF_COUNTRIES_IMPLEMENTING_MANDATO','TOPIC:FINANCIAL-TIMES','bool','at least 12 countries','2030-03-13'));
-- F06: (NUMBER_OF_UN_MEMBER_STATES_ACTIVELY_TARG, TOPIC:WORLD-BANK, >=, over 185, 2031-07-07)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F06, 'F06', 'NUMBER_OF_UN_MEMBER_STATES_ACTIVELY_TARG', 'TOPIC:WORLD-BANK', '>=', 'over 185', '2031-07-07', 0.95, fwd_private.forecast_identity_v1('NUMBER_OF_UN_MEMBER_STATES_ACTIVELY_TARG','TOPIC:WORLD-BANK','>=','over 185','2031-07-07'));
-- F07: (NUMBER_OF_INSTANCES_WHERE_CASE-BY-CASE_C, TOPIC:THE-ECONOMIST, bool, at least 6 instances, 2029-01-16)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F07, 'F07', 'NUMBER_OF_INSTANCES_WHERE_CASE-BY-CASE_C', 'TOPIC:THE-ECONOMIST', 'bool', 'at least 6 instances', '2029-01-16', 0.6, fwd_private.forecast_identity_v1('NUMBER_OF_INSTANCES_WHERE_CASE-BY-CASE_C','TOPIC:THE-ECONOMIST','bool','at least 6 instances','2029-01-16'));
-- F08: (NUMBER_OF_AI_POLICY_DEVELOPMENT_INITIATI, TOPIC:TECHCRUNCH, bool, over 120, 2030-06-09)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F08, 'F08', 'NUMBER_OF_AI_POLICY_DEVELOPMENT_INITIATI', 'TOPIC:TECHCRUNCH', 'bool', 'over 120', '2030-06-09', 0.55, fwd_private.forecast_identity_v1('NUMBER_OF_AI_POLICY_DEVELOPMENT_INITIATI','TOPIC:TECHCRUNCH','bool','over 120','2030-06-09'));
-- F09: (TOTAL_GLOBAL_VENTURE_CAPITAL_INVESTMENT_, TOPIC:PITCHBOOK, bool, exceeding $600 billion, 2031-08-09)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F09, 'F09', 'TOTAL_GLOBAL_VENTURE_CAPITAL_INVESTMENT_', 'TOPIC:PITCHBOOK', 'bool', 'exceeding $600 billion', '2031-08-09', 0.78, fwd_private.forecast_identity_v1('TOTAL_GLOBAL_VENTURE_CAPITAL_INVESTMENT_','TOPIC:PITCHBOOK','bool','exceeding $600 billion','2031-08-09'));
-- F10: (NUMBER_OF_DISTINCT_AI_TECHNOLOGY_ECOSYST, TOPIC:GARTNER, >=, at least 5, 2030-04-29)
INSERT INTO fwd.forecast_identity(book_id,leaf_index,forecast_id,family,event_key,comparator,threshold_canonical,horizon_date,p_sealed,identity_digest) VALUES (:book_id, :leaf_F10, 'F10', 'NUMBER_OF_DISTINCT_AI_TECHNOLOGY_ECOSYST', 'TOPIC:GARTNER', '>=', 'at least 5', '2030-04-29', 0.5, fwd_private.forecast_identity_v1('NUMBER_OF_DISTINCT_AI_TECHNOLOGY_ECOSYST','TOPIC:GARTNER','>=','at least 5','2030-04-29'));
